version: '3'

services:
  ariflow_postgres:
    image: postgres 
    container_name: postgres_airflow
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_AIRFLOW_PASSWORD}
      - POSTGRES_USER=${POSTGRES_AIRFLOW_USER}
      - POSTGRES_DB=airflow
    restart: always
    expose:
    - "5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_AIRFLOW_USER}",
          "-d",
          "airflow"
        ]
      interval: 5s
      retries: 5

  airflow:
    build: ./airflow
    container_name: airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@ariflow_postgres:5432/airflow
      - AIRFLOW_CONN_POSTGRES=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mydb:5432/postgres
    restart: always
    depends_on:
      - ariflow_postgres
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/airflow/dags:/opt/airflow/dags
      - ${PWD}/airflow/logs:/opt/airflow/logs
      - ${PWD}/airflow/plugins:/opt/airflow/plugins 

  jupyter_notebook:
    image: jupyter/scipy-notebook
    container_name: jupyter_notebook
    command: sudo chown -R jovyan:users /home/jovyan/*
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}/jupyter:/home/jovyan/work
    depends_on:
      - database

  database:
    build: 
      context: ./pgvector
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
      interval: 5s
      retries: 5
    volumes:
      - ./pgvector/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql