version: '3'
services:
  ariflow_postgres:
    image: postgres 
    container_name: postgres_airflow
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_AIRFLOW_PASSWORD}
      - POSTGRES_USER=${POSTGRES_AIRFLOW_USER}
      - POSTGRES_DB=airflow
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_AIRFLOW_USER}",
          "-d",
          "airflow"
        ]
      interval: 5s
      retries: 5

  airflow:
    build: ./airflow
    container_name: airflow
    restart: always
    depends_on:
      - ariflow_postgres
    ports:
      - 8080:8080
    volumes:
      - ./airflow/dags:./airflow/dags
      - ./airflow/logs:./airflow/logs
      - ./airflow/plugins:./airflow/plugins

  jupyter_notebook:
    image: jupyter/minimal-notebook
    container_name: jupyter_notebook
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}/jupyter:/jupyter
    depends_on:
      - database

  database:
    build: 
      context: ./pgvector
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
      interval: 5s
      retries: 5
    volumes:
      - ./pgvector/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql

